apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  annotations:
    github.com/project-slug: pedrorault/backstage-test
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: other
  lifecycle: unknown
  owner: team-a
